# Generated by Django 5.0.4 on 2024-05-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='departamento',
        ),
    ]
