# Generated by Django 5.0.4 on 2024-05-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_espacio_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_qr',
            name='imagenqr',
            field=models.ImageField(blank=True, upload_to='qr_images'),
        ),
    ]
