# Generated by Django 5.0.4 on 2024-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_codigo_qr_imagenqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo_qr',
            name='imagenqr',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
