# Generated by Django 5.0.1 on 2024-05-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_codigo_qr_idqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='codigo_qr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.codigo_qr'),
        ),
    ]
