# Generated by Django 5.0.4 on 2024-05-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_espacio_codigo_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='evidencia',
        ),
        migrations.AddField(
            model_name='alerta',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.espacio'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='evidencia1',
            field=models.ImageField(blank=True, upload_to='evidencias'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='evidencia2',
            field=models.ImageField(blank=True, upload_to='evidencias'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='evidencia3',
            field=models.ImageField(blank=True, upload_to='evidencias'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='nombre_espacio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
