# Generated by Django 5.0.4 on 2024-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_qrtoken_alter_alerta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='evidencia1',
            field=models.ImageField(upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='evidencia2',
            field=models.ImageField(upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nombre_espacio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solucionalerta',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
