# Generated by Django 5.0.4 on 2024-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_alerta_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='evidencia1',
            field=models.ImageField(blank=True, upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='evidencia2',
            field=models.ImageField(blank=True, upload_to='evidencias'),
        ),
        migrations.AlterField(
            model_name='solucionalerta',
            name='fecha_resolucion',
            field=models.DateTimeField(null=True),
        ),
    ]
