# Generated by Django 5.0.4 on 2024-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_alerta_evidencia1_alter_alerta_evidencia2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucionalerta',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
