# Generated by Django 5.0.6 on 2024-06-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_alter_solucionalerta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
