# Generated by Django 5.0.6 on 2024-06-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.jpg', upload_to='perfil/'),
        ),
    ]
