# Generated by Django 5.0.4 on 2024-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='perfil/default.png', upload_to='perfil/'),
        ),
    ]
